# Makefile for 68000 operating system
#
# Copyright (C) 2021 Dennis May
# First Published 2021
#
# This file is part of 68000 Software Suite.
#
# 68000 Software Suite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# 68000 Software Suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with 68000 Software Suite.  If not, see <https://www.gnu.org/licenses/>.
#

ifeq ($(PROG),)
PROGNAME:=68kOS
else
PROGNAME:=$(PROG)
endif

COMMON_DIR:=../Common
LINK_SCRIPT:=68kOS.sct
include $(COMMON_DIR)/common.mak
